import type { MDbMovie } from "../../types/typesMDb";
import type { MediaDiaryWithId } from "../../types/typesMedia";

export const mockMovieDiaryWithId: MediaDiaryWithId = {
  artist: "Edgar Wright",
  mediaId: "776485",
  title: "The Sparks Brothers",
  releasedDecade: 2020,
  poster: "1O0J20bIE2vjSdj1IlHhe9D29CM",
  genre: "documentary",
  releasedDate: "2021-06-18T07:00:00.000Z",
  bookmark: false,
  rating: 3.5,
  addedDate: "2021-06-21T01:54:44.357Z",
  loggedBefore: false,
  id: "fFS2Alf0GU8TLUXp5Jkm",
  diaryDate: "2021-06-21T01:54:34.606Z",
  type: "movie",
  releasedYear: 2021,
  diaryYear: 2021,
};

export const mockMovieFetchData: MDbMovie = {
  adult: false,
  backdrop_path: "/kCiMExsYuNhYluHxPP2OTmWw7hp.jpg",
  budget: 18000000,
  genres: [
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 28,
      name: "Action",
    },
  ],
  homepage: "http://www.indianajones.com",
  id: 85,
  imdb_id: "tt0082971",
  original_language: "en",
  original_title: "Raiders of the Lost Ark",
  overview:
    "When Dr. Indiana Jones – the tweed-suited professor who just happens to be a celebrated archaeologist – is hired by the government to locate the legendary Ark of the Covenant, he finds himself up against the entire Nazi regime.",
  popularity: 31.224,
  poster_path: "/awUGN7ZCNq2EUTdpVaHDX23anOZ.jpg",
  release_date: "1981-06-12",
  revenue: 389925971,
  runtime: 115,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline:
    "Indiana Jones - the new hero from the creators of JAWS and STAR WARS.",
  title: "Raiders of the Lost Ark",
  video: false,
  vote_average: 7.9,
  vote_count: 9192,
  credits: {
    cast: [
      {
        adult: false,
        gender: 2,
        id: 3,
        known_for_department: "Acting",
        name: "Harrison Ford",
        original_name: "Harrison Ford",
        popularity: 11.434,
        profile_path: "/klPehAfaQDatLLQ8dN4lMcb4ESo.jpg",
        cast_id: 2,
        character: "Indiana Jones",
        credit_id: "52fe4215c3a36847f8002a05",
        order: 0,
      },
      {
        adult: false,
        gender: 1,
        id: 650,
        known_for_department: "Acting",
        name: "Karen Allen",
        original_name: "Karen Allen",
        popularity: 2.646,
        profile_path: "/eo2hrUwTsfrVVhXycH0lC0WQMsd.jpg",
        cast_id: 3,
        character: "Marion Ravenwood",
        credit_id: "52fe4215c3a36847f8002a09",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 652,
        known_for_department: "Acting",
        name: "Paul Freeman",
        original_name: "Paul Freeman",
        popularity: 1.237,
        profile_path: "/mLDHLughdhSe6AqsklX0Zhjk9Rx.jpg",
        cast_id: 4,
        character: "Dr. René Belloq",
        credit_id: "52fe4215c3a36847f8002a0d",
        order: 2,
      },
      {
        adult: false,
        gender: 2,
        id: 655,
        known_for_department: "Acting",
        name: "John Rhys-Davies",
        original_name: "John Rhys-Davies",
        popularity: 3.422,
        profile_path: "/dvT1NPY8CXIVQh0O1h6rpfYOgKz.jpg",
        cast_id: 6,
        character: "Sallah",
        credit_id: "52fe4215c3a36847f8002a15",
        order: 3,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 2,
        id: 1,
        known_for_department: "Directing",
        name: "George Lucas",
        original_name: "George Lucas",
        popularity: 7.844,
        profile_path: "/WCSZzWdtPmdRxH9LUCVi2JPCSJ.jpg",
        credit_id: "52fe4215c3a36847f8002a5b",
        department: "Editing",
        job: "Editor",
      },
      {
        adult: false,
        gender: 2,
        id: 1,
        known_for_department: "Directing",
        name: "George Lucas",
        original_name: "George Lucas",
        popularity: 7.844,
        profile_path: "/WCSZzWdtPmdRxH9LUCVi2JPCSJ.jpg",
        credit_id: "52fe4215c3a36847f8002a3d",
        department: "Production",
        job: "Executive Producer",
      },
      {
        adult: false,
        gender: 2,
        id: 1,
        known_for_department: "Directing",
        name: "George Lucas",
        original_name: "George Lucas",
        popularity: 7.844,
        profile_path: "/WCSZzWdtPmdRxH9LUCVi2JPCSJ.jpg",
        credit_id: "58959632c3a36822e0003388",
        department: "Writing",
        job: "Story",
      },
      {
        adult: false,
        gender: 2,
        id: 491,
        known_for_department: "Sound",
        name: "John Williams",
        original_name: "John Williams",
        popularity: 2.672,
        profile_path: "/KFyMqUWeiBdP9tJcZyGWOqnrgK.jpg",
        credit_id: "52fe4215c3a36847f8002a49",
        department: "Sound",
        job: "Original Music Composer",
      },
      {
        adult: false,
        gender: 2,
        id: 488,
        known_for_department: "Directing",
        name: "Steven Spielberg",
        original_name: "Steven Spielberg",
        popularity: 8.481,
        profile_path: "/tZxcg19YQ3e8fJ0pOs7hjlnmmr6.jpg",
        credit_id: "52fe4215c3a36847f8002a01",
        department: "Directing",
        job: "Director",
      },
    ],
  },
  videos: {
    results: [
      {
        id: "533ec652c3a368544800009d",
        iso_639_1: "en",
        iso_3166_1: "US",
        key: "FSKhhPUyVV0",
        name: "Harrison Ford on RAIDERS OF THE LOST ARK and Indiana Jones",
        site: "YouTube",
        size: 480,
        type: "Featurette",
      },
      {
        id: "5614796d92514172d6003be0",
        iso_639_1: "en",
        iso_3166_1: "US",
        key: "XkkzKHCx154",
        name: "HD - Raiders of the Lost Ark (1981) Theatrical Trailer",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
      },
      {
        id: "533ec652c3a368544800009c",
        iso_639_1: "en",
        iso_3166_1: "US",
        key: "X4DOyCPRlx0",
        name: "Steven Spielberg on RAIDERS OF THE LOST ARK",
        site: "YouTube",
        size: 480,
        type: "Featurette",
      },
      {
        id: "54732a549251416dc30019fd",
        iso_639_1: "en",
        iso_3166_1: "US",
        key: "S6ruDPy5isk",
        name: "Ti West on RAIDERS OF THE LOST ARK",
        site: "YouTube",
        size: 1080,
        type: "Featurette",
      },
      {
        id: "59892334c3a36874ad008280",
        iso_639_1: "en",
        iso_3166_1: "US",
        key: "jj7eN9avhEc",
        name: "Indiana Jones and the Raiders of the Lost Ark (1981) Re-Issue Trailer",
        site: "YouTube",
        size: 1080,
        type: "Trailer",
      },
      {
        id: "5989234e9251414bac0094a7",
        iso_639_1: "en",
        iso_3166_1: "US",
        key: "_RmmbPdckSg",
        name: "Indiana Jones and the Raiders of the Lost Ark (1981) Teaser",
        site: "YouTube",
        size: 1080,
        type: "Teaser",
      },
    ],
  },
  "watch/providers": {
    results: {
      US: {
        link: "https://www.themoviedb.org/movie/85-raiders-of-the-lost-ark/watch?locale=US",
        rent: [
          {
            display_priority: 2,
            logo_path: "/q6tl6Ib6X5FT80RMlcDbexIo4St.jpg",
            provider_id: 2,
            provider_name: "Apple iTunes",
          },
        ],
        buy: [
          {
            display_priority: 2,
            logo_path: "/q6tl6Ib6X5FT80RMlcDbexIo4St.jpg",
            provider_id: 2,
            provider_name: "Apple iTunes",
          },
        ],
        flatrate: [
          {
            display_priority: 13,
            logo_path: "/pkAHkRhIq3Iu0ZlEhDzbguSlyZF.jpg",
            provider_id: 531,
            provider_name: "Paramount Plus",
          },
          {
            display_priority: 16,
            logo_path: "/kUEY5arlNmaFWeKp6XaCkKafBry.jpg",
            provider_id: 582,
            provider_name: "Paramount+ Amazon Channel",
          },
          {
            display_priority: 36,
            logo_path: "/kwCsPIK3KA1YTXq7XxXaVDhTxLY.jpg",
            provider_id: 78,
            provider_name: "CBS",
          },
        ],
      },
    },
  },
};
